default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

beta:
  <<: *default
  database: api_beta

production:
  <<: *default
  database: api_production
